kaportfolio_homepage:
    pattern:  /
    defaults: { _controller: KaPortfolioBundle:Portfolio:index }

kaportfolio_work:
    pattern:  /work
    defaults: { _controller: KaPortfolioBundle:Portfolio:work }

kaportfolio_cv:
    pattern:  /cv
    defaults: { _controller: KaPortfolioBundle:Portfolio:cv }

kaportfolio_contact:
    pattern:  /contact
    defaults: { _controller: KaPortfolioBundle:Portfolio:contact }

kaportfolio_link:
    pattern:  /links
    defaults: { _controller: KaPortfolioBundle:Portfolio:link }

kaportfolio_add_project:
    pattern:  /add-project
    defaults: { _controller: KaPortfolioBundle:Portfolio:addProject }

kaportfolio_add_techno:
    pattern:  /add-technology
    defaults: { _controller: KaPortfolioBundle:Portfolio:addTechnology }
